### ISSUE TITLE
web/client: err  TypeError: Cannot read property 'hash' of undefined

### ISSUE THREAD

**Issue by nictuku** [nictuku/stardew-rocks#43]
This happens when I run jspm install with after #42 
```
err  TypeError: Cannot read property 'hash' of undefined
    at computePackageHash (/usr/lib/node_modules/jspm/lib/package.js:741:65)
    at Promise.resolve.then.then.then.then.then.Promise.resolve.then.then.lookupObj (/usr/lib/node_modules/jspm/lib/package.js:505:18)
    at tryCatcher (/usr/lib/node_modules/jspm/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/usr/lib/node_modules/jspm/node_modules/bluebird/js/release/promise.js:503:31)
    at Promise._settlePromise (/usr/lib/node_modules/jspm/node_modules/bluebird/js/release/promise.js:560:18)
    at Promise._settlePromise0 (/usr/lib/node_modules/jspm/node_modules/bluebird/js/release/promise.js:605:10)
    at Promise._settlePromises (/usr/lib/node_modules/jspm/node_modules/bluebird/js/release/promise.js:684:18)
    at Promise._fulfill (/usr/lib/node_modules/jspm/node_modules/bluebird/js/release/promise.js:629:18)
    at Promise._resolveCallback (/usr/lib/node_modules/jspm/node_modules/bluebird/js/release/promise.js:424:57)
    at Promise._settlePromiseFromHandler (/usr/lib/node_modules/jspm/node_modules/bluebird/js/release/promise.js:515:17)
    at Promise._settlePromise (/usr/lib/node_modules/jspm/node_modules/bluebird/js/release/promise.js:560:18)
    at Promise._settlePromise0 (/usr/lib/node_modules/jspm/node_modules/bluebird/js/release/promise.js:605:10)
    at Promise._settlePromises (/usr/lib/node_modules/jspm/node_modules/bluebird/js/release/promise.js:684:18)
    at Promise._fulfill (/usr/lib/node_modules/jspm/node_modules/bluebird/js/release/promise.js:629:18)
    at PromiseArray._resolve (/usr/lib/node_modules/jspm/node_modules/bluebird/js/release/promise_array.js:125:19)
    at PromiseArray._promiseFulfilled (/usr/lib/node_modules/jspm/node_modules/bluebird/js/release/promise_array.js:143:14)
    at Promise._settlePromise (/usr/lib/node_modules/jspm/node_modules/bluebird/js/release/promise.js:565:26)
    at Promise._settlePromise0 (/usr/lib/node_modules/jspm/node_modules/bluebird/js/release/promise.js:605:10)
    at Promise._settlePromises (/usr/lib/node_modules/jspm/node_modules/bluebird/js/release/promise.js:684:18)
    at Promise._fulfill (/usr/lib/node_modules/jspm/node_modules/bluebird/js/release/promise.js:629:18)
    at /usr/lib/node_modules/jspm/node_modules/bluebird/js/release/nodeback.js:42:21
    at Object.oncomplete (fs.js:108:15)

```

I'm probably doing something wrong as usual :-). 

I'm running the deploy.sh script:

bash -x deploy.sh dev

**Comment by gumbyscout** [comment]
Rebuilt the jspm packages project, hopefully this will fix errors with jspm install. See pr #44 .
